export interface PresetTrolley {
  id: string;
  name: string;
  description: string;
  emoji: string;
  items: string[];
}

export const PRESET_TROLLEYS: PresetTrolley[] = [
  {
    id: "student",
    name: "Student",
    description: "Budget-friendly basics for flat life",
    emoji: "\uD83C\uDF93",
    items: [
      "instant noodles",
      "white bread",
      "eggs",
      "milk 2L",
      "butter",
      "pasta 500g",
      "pasta sauce",
      "rice 1kg",
      "canned tuna",
      "bananas",
      "cheese block",
      "instant coffee",
    ],
  },
  {
    id: "family",
    name: "Family of 4",
    description: "Weekly essentials for the household",
    emoji: "\uD83C\uDFE0",
    items: [
      "chicken breast",
      "beef mince 500g",
      "bread",
      "milk 2L",
      "eggs",
      "butter",
      "cheese",
      "rice 1kg",
      "pasta",
      "cereal",
      "yoghurt",
      "apples",
      "bananas",
      "broccoli",
      "carrots",
      "potatoes",
      "onions",
      "canned tomatoes",
      "cooking oil",
      "orange juice",
    ],
  },
  {
    id: "couple",
    name: "Couple",
    description: "Balanced shop for two",
    emoji: "\uD83D\uDC65",
    items: [
      "chicken thigh",
      "salmon",
      "bread",
      "eggs",
      "milk 1L",
      "avocado",
      "salad mix",
      "pasta",
      "rice",
      "cheese",
      "coffee",
      "yoghurt",
      "tomatoes",
      "mushrooms",
    ],
  },
  {
    id: "health",
    name: "Health-Conscious",
    description: "Clean eating and whole foods",
    emoji: "\uD83E\uDD66",
    items: [
      "chicken breast",
      "salmon fillet",
      "brown rice",
      "eggs",
      "spinach",
      "broccoli",
      "avocado",
      "blueberries",
      "almonds",
      "rolled oats",
      "greek yoghurt",
      "olive oil",
      "sweet potato",
      "quinoa",
    ],
  },
  {
    id: "budget",
    name: "Budget",
    description: "Maximum value, minimum spend",
    emoji: "\uD83D\uDCB0",
    items: [
      "white bread",
      "eggs",
      "milk 2L",
      "beef mince",
      "rice 1kg",
      "pasta 500g",
      "canned baked beans",
      "canned tomatoes",
      "frozen mixed vegetables",
      "bananas",
      "potatoes",
      "onions",
      "cooking oil",
      "rolled oats",
    ],
  },
  {
    id: "vegan",
    name: "Plant-Based",
    description: "100% vegan weekly staples",
    emoji: "\uD83C\uDF31",
    items: [
      "tofu",
      "oat milk",
      "bread",
      "rice",
      "pasta",
      "chickpeas canned",
      "lentils",
      "canned tomatoes",
      "avocado",
      "bananas",
      "spinach",
      "broccoli",
      "peanut butter",
      "olive oil",
      "rolled oats",
    ],
  },
];
